export const FETCH_SMURFS_START = "FETCH_SMURFS_START";
export const FETCH_SMURFS_SUCCESS = "FETCH_SMURFS_SUCCESS";
export const FETCH_SMURFS_FAILURE = "FETCH_SMURFS_FAILURE";

export const HANDLE_TEXT_INPUT_CHANGE = "HANDLE_TEXT_INPUT_CHANGE";
export const CLEAR_TEXT_INPUTS = "CLEAR_TEXT_INPUTS";

export const ADD_SMURF_START = "ADD_SMURF_START";
export const ADD_SMURF_SUCCESS = "ADD_SMURF_SUCCESS";
export const ADD_SMURF_FAILURE = "ADD_SMURF_FAILURE";

export const SELECT_SMURF_START = "SELECT_SMURF_START";
export const SELECT_SMURF_SUCCESS = "SELECT_SMURF_SUCCESS";
export const SELECT_SMURF_FAILURE = "SELECT_SMURF_FAILURE";

export const DELETE_SMURF_START = "DELETE_SMURF_START";
export const DELETE_SMURF_SUCCESS = "DELETE_SMURF_SUCCESS";
export const DELETE_SMURF_FAILURE = "DELETE_SMURF_FAILURE";

export const TOGGLE_UPDATE_MODE = "TOGGLE_UPDATE_MODE";

export const UPDATE_SMURF_START = "UPDATE_SMURF_START";
export const UPDATE_SMURF_SUCCESS = "UPDATE_SMURF_SUCCESS";
export const UPDATE_SMURF_FAILURE = "UPDATE_SMURF_FAILURE";
